name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
          
      - name: Move to project directory
        run: cd TicTacToe

      - name: Run tests
        run: mvn test --file TicTacToe/pom.xml

      - name: Build project
        if: github.ref == 'refs/heads/main'
        run: mvn -B package --file TicTacToe/pom.xml