name: Java CI with Maven

on:
  push:
    branches:
      - HP/testCalculator
  pull_request:
    branches:
      - HP/testCalculator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v3
      
      - name: set JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: build project
        run: mvn -B package --file pom.xml
      
      - name: run test
        run: mvn test