name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      
      - name: Install Xvfb for GUI testing
        run: sudo apt-get install -y xvfb
      
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
      - name: Move to project directory
        run: cd TicTacToe

      - name: Run tests with Xvfb
        env:
          DISPLAY: :99
        run: mvn test --file TicTacToe/pom.xml

      - name: Build project with Xvfb
        if: github.ref == 'refs/heads/main'
        env:
          DISPLAY: :99
        run: mvn -B package --file TicTacToe/pom.xml
