name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Install Xvfb for GUI-based tests
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      # Start Xvfb for GUI testing
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
      # Run HEADLESS TESTS (No UI needed)
      - name: Run Headless Tests
        # env:
        #   DISPLAY: :99
        run: mvn test -Djava.awt.headless=true -Dtest=TCO1Test

      # Run GUI TESTS (Require Virtual Display)
      - name: Run GUI Tests with Xvfb
        env:
          DISPLAY: :99
        run: mvn test -Djava.awt.headless=false -Dtest=\*GUITest

      # Build project only if tests pass
      - name: Build project
        if: success()
        working-directory: TicTacToe
        env:
          DISPLAY: :99
        run: mvn -B package
