name: Java CI with Maven

on:
  push:
    branches:
      - HV/To-do-list
  pull_request:
    branches:
      - HV/To-do-list

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest stable Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch the repository code

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven  # Cache Maven dependencies

      - name: Run unit tests (headless mode)
        working-directory: TicTacToe  # Ensure this is the correct path
        run: mvn test -Djava.awt.headless=true

      - name: Build project (only on main branch)
        if: github.ref == 'refs/heads/main'
        working-directory: TicTacToe
        run: mvn -B package
