name: Java CI with Maven

on:
  push:
    branches:
      - AF/TC-02---Win-Condition
  pull_request:
    branches:
      - AF/TC-02---Win-Condition

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run tests in Headless Mode
        working-directory: TicTacToe
        run: mvn test -Djava.awt.headless=true

      - name: Build project
        if: github.ref == 'refs/heads/main'
        working-directory: TicTacToe
        run: mvn -B package
